id: f458cae7-a7bb-46fc-86e3-b510ab917d28
name: Catalog Service - Prod
values:
  - key: baseUrl
    value: 'http://localhost:3003'
    enabled: true
    type: default
_postman_variable_scope: environment
color: 0
_postman_exported_at: '2026-02-17T22:38:02.652Z'
_postman_exported_using: Postman/11.0.0
