id: 3984427d-dd4d-4432-97c3-27907409d0df
name: Catalog Service -Dev
values:
  - key: baseUrl
    value: 'http://localhost:3003'
    enabled: true
    type: default
_postman_variable_scope: environment
color: 120
